all:
  children:
    control_plane:
      hosts:
        cp1:
          ansible_host: 10.0.0.11
        cp2:
          ansible_host: 10.0.0.12
        cp3:
          ansible_host: 10.0.0.13

    workers:
      hosts:
        worker1:
          ansible_host: 10.0.0.21
        worker2:
          ansible_host: 10.0.0.22
        worker3:
          ansible_host: 10.0.0.23
